retention_days: 5

cameras:
  - id: garage_webcam
    type: webcam  # 'webcam' or 'rtsp'
    index: 0

  - id: lounge_rtsp
    type: rtsp
    url: "rtsps://192.168.10.176:7441/pam607F6TjwKqzzS?enableSrtp"

publisher:
  port: 5555

subscriber:
  throttle_n: 10   # 0 = no throttle
  deduplicate: true
