camera:
  type: rtsp       # 'webcam' or 'rtsp'
  url: "rtsps://192.168.10.176:7441/pam607F6TjwKqzzS?enableSrtp"
  index: 0         # Only used if type == 'webcam'

publisher:
  port: 5555

subscriber:
  throttle_n: 0   # 0 = no throttle
  deduplicate: true
